version: "2.2"
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    ports:
    - 1883:1883 
    - 9001:9001
    volumes:
    - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf 
    - ./mosquitto/data:/mosquitto/data 
    - ./mosquitto/log:/mosquitto/log
    # docker run --rm -p 1883:1883 -p 9001:9001 -v (pwd)/config/mosquitto.conf:/mosquitto/config/mosquitto.conf -v (pwd)/mosquitto/data:/mosquitto/data -v (pwd)/mosquitto/log:/mosquitto/log eclipse-mosquitto:1.6.9
  producer:
    image: node:14.2.0-alpine3.11
    volumes:
    - ./producer:/app
    working_dir: /app
    command: node index.js
  consumer:
    image: node:14.2.0-alpine3.11
    volumes:
    - ./consumer:/app
    working_dir: /app
    command: node index.js
  consumer-web:
    image: nginx:1.17.10-alpine
    ports:
    - 80:80
    volumes:
    - ./consumer-web:/usr/share/nginx/html
